<?php
$form = $this->userAccountForm;
$errorMessage = $this->errorMessage;
$userCreditHistory = $this->userCreditHistory;
$currentDate = $this->currentDate;
$form->prepare();
$form->setAttribute('name', 'user_account');
$form->setAttribute('id', 'user_account');
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'row');

$urlArray = array(
    'data_url' => $this->url('list-associate-user'),
);

/* Reading user details from authenticate view helper */
$authenticationService = $this->authenticate_view_helper();
$userObject = $authenticationService->getIdentity();
?>
<input type="hidden" id="url-array" value='<?php echo json_encode($urlArray); ?>'> 
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 col-lg-offset-2 col-md-offset-1 mar-b40">
            <div class="row mar-t30">
                <div class="col-sm-4 txtc">
                    <p class="font-size-xl font-family-bold stats pad-t20"><?php echo $userCreditHistory['remainingPoints'] ?></p>
                    <h3 class="font-size-m font-family-md">Analysis Credit Remaining on <?php echo $currentDate ?></h3>
                </div>
                <div class="col-sm-4 txtc">
                    <p class="font-size-xl font-family-bold stats pad-t20"><?php echo $userCreditHistory['usedCreditPoints'] ?></p>
                    <h3 class="font-size-m font-family-md">Analysis Credit Used</h3>
                </div>
                <div class="col-sm-4 txtc">
                    <p class="font-size-xl font-family-bold stats pad-t20"><?php echo $userCreditHistory['expiredCredits'] ?></p>
                    <h3 class="font-size-m font-family-md">Analysis Credit Expired</h3>
                </div>                                    
            </div>
            
            <?php if ($this->successMessage) { ?>            
                <script>
                    setTimeout("$('.alert-success').fadeOut(2000);", 5000);
                </script>
                <div class="alert-success"><?php echo $this->successMessage; ?></div>
            <?php } ?>
                
            <?php if ($this->cancelMessage) { ?>                    
                <script>
                    setTimeout("$('.alert-error').fadeOut(2000);", 5000);                       
                </script>                    
                <div class="alert-error"><?php echo $this->cancelMessage; ?></div>
            <?php } ?>             
                <div class="clearfix">
            <h2 class="font-size-l font-caps-up">Personal Information</h2>
            <?php echo $this->form()->openTag($form); ?>
            <div class="col-sm-6">
                <div class="form-group <?php if ($errorMessage['first_name']) echo "error"; ?>" id="first_nameErrorClass">
                    <span class="form-control-anim ">             
                      <!--  <input class="form-control-field" type="text" value="<?php echo $userObject->getFirstName() ?>" > -->
                        <?php echo $this->formRow($form->get('first_name')) . "\n"; ?>
                        <label class="form-control-label">                                                                      
                            <span id="first_nameErrorMsg" class="form-control-label-content" data-text='First name'>
                                <?php echo ($errorMessage['first_name']) ? $errorMessage['first_name'] : "First name"; ?>
                            </span>                                                                
                        </label>
                    </span>                   
                </div>                           
            </div>
            <div class="col-sm-6">
                <div class="form-group <?php if ($errorMessage['last_name']) echo "error"; ?>" id="last_nameErrorClass">
                    <span class="form-control-anim ">             
                        <?php echo $this->formRow($form->get('last_name')) . "\n"; ?>
                        <label class="form-control-label">                                                              
                            <span id="last_nameErrorMsg" class="form-control-label-content" data-text='Last name'>
                                <?php echo ($errorMessage['last_name']) ? $errorMessage['last_name'] : "Last name"; ?>
                            </span>                                
                        </label>
                    </span>                   
                </div>                           
            </div> 
            <div class="col-sm-6">
                <div class="form-group">
                    <span class="form-control-anim">             
                        <?php echo $this->formRow($form->get('email')) . "\n"; ?>
                        <label class="form-control-label">                              
                            <span class="form-control-label-content">Email Address</span>
                        </label>
                    </span>                   
                </div>                           
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <span  class="form-control-anim">             
                        <?php echo $this->formRow($form->get('phone_number')) . "\n"; ?>
                        <label class="form-control-label">                              
                            <span class="form-control-label-content">Phone number</span>
                        </label>
                    </span>
                </div>
            </div>
            </div>               
                
            <h2 class="font-size-l font-caps-up">Change Password</h2>
            <div class="row">
            <div class="clearfix">
                <div class="col-sm-6">
                    <div class="form-group <?php if ($errorMessage['old_password']) echo "error"; ?>" id="old_passwordErrorClass">
                        <span class="form-control-anim">             
                            <?php echo $this->formRow($form->get('old_password')) . "\n"; ?>
                            <label class="form-control-label">                                                                  
                                <span id="old_passwordErrorMsg" class="form-control-label-content" data-text='Old password'>
                                    <?php echo ($errorMessage['old_password']) ? $errorMessage['old_password'] : "Old password"; ?>
                                </span>                                    
                            </label>
                        </span>                   
                    </div>                           
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group <?php if ($errorMessage['password']) echo "error"; ?>" id="passwordErrorClass">
                    <span class="form-control-anim ">             
                        <?php echo $this->formRow($form->get('password')) . "\n"; ?>
                        <label class="form-control-label">                               
                            <span id="passwordErrorMsg" class="form-control-label-content" data-text='New password'>
                                <?php echo ($errorMessage['password']) ? $errorMessage['password'] : "New password"; ?>
                            </span>                                
                        </label>
                    </span>                   
                </div>                           
            </div>
            <div class="col-sm-6">
                <div class="form-group <?php if ($errorMessage['confirm_password']) echo "error"; ?>" id="confirm_passwordErrorClass" >
                    <span class="form-control-anim ">             
                        <?php echo $this->formRow($form->get('confirm_password')) . "\n"; ?>
                        <label class="form-control-label">                                                              
                            <span id="confirm_passwordErrorMsg" class="form-control-label-content" data-text='Re-type new password'>
                                <?php echo ($errorMessage['confirm_password']) ? $errorMessage['confirm_password'] : "Re-type new password"; ?>
                            </span>

                        </label>
                    </span>                   
                </div>                           
            </div>                                                   
            </div>

            <h2 class="font-size-l font-caps-up">Address</h2>
            <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <span class="form-control-anim">             
                        <?php echo $this->formRow($form->get('address_1')) . "\n"; ?>
                        <label class="form-control-label">                              
                            <span class="form-control-label-content">Address1</span>
                        </label>
                    </span>                   
                </div>                           
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <span class="form-control-anim">             
                        <?php echo $this->formRow($form->get('address_2')) . "\n"; ?>
                        <label class="form-control-label">                              
                            <span class="form-control-label-content">Address2</span>
                        </label>
                    </span>                   
                </div>                           
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <span class="form-control-anim">             
                        <?php echo $this->formRow($form->get('city')) . "\n"; ?>
                        <label class="form-control-label">                              
                            <span class="form-control-label-content">City</span>
                        </label>
                    </span>                   
                </div>                           
            </div>   
            <div class="col-sm-6">
                <div class="form-group">
                    <span class="form-control-anim">             
                        <?php echo $this->formRow($form->get('state')) . "\n"; ?>
                        <label class="form-control-label">                              
                            <span class="form-control-label-content">State</span>
                        </label>
                    </span>                   
                </div>                           
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <span class="form-control-anim">             
                        <?php echo $this->formRow($form->get('country')); ?>
                        <label class="form-control-label">                              
                            <span class="form-control-label-content">Country</span>
                        </label>
                    </span>                   
                </div>                           
            </div>
            <div class="col-sm-6">
                <div class="form-group" id="zip_codeErrorClass">
                    <span class="form-control-anim">             
                        <?php echo $this->formRow($form->get('zip_code')) . "\n"; ?>
                        <label class="form-control-label">                              
                            <span id="zip_codeErrorMsg" class="form-control-label-content">Zip Code</span>
                        </label>
                    </span>                   
                </div>                           
            </div>  
            <div class="col-sm-12">
                <?php echo $this->formRow($form->get('submit_user_account')); ?>             
                <a class="btn btn-link" href="<?php echo $this->url('user-account') ?>">Reset</a>
            </div>                
            </div>
            
            <?php if (isset($this->role) AND $this->role == 'user'):?>
               <hr class="clearfix mar-t30">
                <div class="row">
                    <div class="col-sm-12 mar-t10 mar-b10">
                        <span data-toggle="modal" data-acp-type="Associate User" data-target="#add-associate-user" class="pull-right acp-risk-edit">  
                            <button type="button" class="btn btn-default btn-small">Add Associate User</button>        
                        </span>
                    </div>                          
                </form>             
                </div> 
                <div class="alert-success" style="display:none"></div>                               
                 <div class="clearfix">
                    <div class="table-responsive">
                        <table class="table custom-table" id="associate-user">
                            <thead>
                                <tr>
                                    <th>FIRST NAME<a href="javascript:void"></a></th>
                                    <th>LAST NAME<a href="javascript:void"></a></th>
                                    <th>EMAIL ADDRESS<a href="javascript:void"></a></th>
                                    <th>ACTIONS</th>                    
                                </tr>
                            </thead>            
                        </table>   
                    </div>
                 </div>
            <?php endif;?>
        </div>        
    </div>    
</div>


<!-- Add Associate user Model box -->
<div class="modal fade" id="add-associate-user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Associate User</h4>
      </div>
      <div class="modal-body">
        <form action="">
            <input type="hidden" id="edit_acp_id_hidden" >
            <input type="hidden" id="edit_acp_type_hidden" >
            <div class="form-group" id="associate_first_nameErrorClass">
                <span class="form-control-anim form-control-selected">             
                    <input class="form-control-field" type="text" id="associate_first_name">
                    <label class="form-control-label">                              
                      <span id="associate_first_nameErrorMsg" class="form-control-label-content acp-label-id">First Name</span>
                    </label>
                </span>                    
            </div>
            <div class="form-group" id="associate_last_nameErrorClass">
                <span class="form-control-anim form-control-selected">             
                    <input class="form-control-field" type="text" id="associate_last_name">
                    <label class="form-control-label">                              
                      <span id="associate_last_nameErrorMsg" class="form-control-label-content acp-label-id">Last Name</span>
                    </label>
                </span>                    
            </div>
            <div class="form-group" id="associate_emailErrorClass">
                <span class="form-control-anim form-control-selected">             
                    <input class="form-control-field" type="email" id="associate_email">
                    <label class="form-control-label">                              
                      <span id="associate_emailErrorMsg" class="form-control-label-content acp-label-id">Email</span>
                    </label>
                </span>                    
            </div>            
            <div class="clearfix">
                  <button type="button" class="btn btn-default" id="add-associate-user-submit">OK</button>
                  <button type="button" class="btn btn-link" data-dismiss="modal" aria-label="Close">Cancel</button>                    
            </div>
        </form>                      
      </div>
    </div>
  </div>
</div> 

<script>
    var add_associate_url = '<?php echo $this->url('add-associate-user'); ?>';
    var delete_associate_url = '<?php echo $this->url('delete-associate-user'); ?>';
</script>