<?php
    require_once __DIR__ . '/header-mail.phtml';
?>
<?php
    $userObject = $this->user;
?>
<p>
    Someone recently requested for the password to be reset for username: <?php echo $userObject->getUsername();  ?> 
    <?php $link =  "http://".$_SERVER['HTTP_HOST']."/reset-password/".$this->passwordResetKey; ?><br/>
    <br>Please visit the link below to reset your password.
    <br><?php echo "<a href='$link'>$link</a>"; ?>
    <br>Link not working? Copy and paste the above link into your browser.<br/><br/>
</p>
<?php
    require_once __DIR__ . '/mail-footer.phtml';
?>


        


       