<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Audit Companion mail</title>
    <style>
    body{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif; font-size: 14px; color: #666666;}
    qgrid-a{ color: #f47521;}
    p{ margin-top: 0px;}
    .email-footer{ color: #989898; padding-top: 20px;}
    </style>
  </head>

  <body>
    <table style="width:700px;border: 4px solid #e5e5e5;border-radius: 3px;" cellpadding="0" cellspacing="0">
        <tr>
            <td style=" text-align: center; padding: 15px 0px 10px 0px;"><img src="<?php if (isset($this->appBaseLink)) {echo $this->appBaseLink . "/img/logo_small.png";} else { echo "http://" .  $_SERVER['HTTP_HOST'] . "/img/logo_small.png";} ?>" /></td>
        </tr>
        <tr>
            <td>
               <div style="border-top:1px solid #e5e5e5; padding:30px 30px 15px 30px;">
                <p>Dear <?php
                
                if (is_object($this->user)) {
                    $userName = ucwords($this->user->getFirstName()); 
                } else if (count($this->orderArray)>0) {
                    $userName = ucwords($this->orderArray['full_name']); 
                }                                
                echo $userName; ?>,</p>