<div class="email-footer">
    <?php
        $url = "support@auditcompanion.biz";
    ?>
                    <p>If you have any other questions, suggestions, business proposal or would like to get in touch with us for any reason whatsoever send us mail to <a href="<?php echo $url; ?>"><?php echo $url; ?></a><br/><br/>
                        Thanks,<br/>
                        The Audit Companion Team<br/>
                        —<br/>
                        Web: http://auditcompanion.biz<br/>
                        Email: support@auditcompanion.biz</p>
                </div>
               </div>
            </td>
        </tr>
    </table>
  </body>
</html>