<?php 
include('commonMenuUtility.php');
$url = $_SERVER['REQUEST_URI']; 
$cssMenu = array('/manage-users', '/list-system-activity');
$cssMenu[$url] = 'active';
function headerHighlight($inputArray){
	$url_break_up = explode('/', $_SERVER['REQUEST_URI']);
	foreach ($url_break_up as $url_current) {
		if (in_array($url_current, $inputArray)) {
			return 'active';
		}
	}
}
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headTitle() ?>

    <!-- Bootstrap core CSS -->    
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Custom styles for this template -->    
    <link href="/css/main.css" rel="stylesheet">
    <link href="/css/jquery.dataTables.css" rel="stylesheet">
    <link href="/css/jquery-ui.css.css" rel="stylesheet">
    <link href="/img/favicon.ico" rel="shortcut icon">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/admin"><img src="/img/logo_small.png" /></a>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav navbar-right custom-nav">
            <li class="navbar-text mar-t10">Welcome <?php echo $userName ?></li>                        
       <li class="dropdown custom-dd">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            
            <li class="<?php echo headerHighlight(array('manage-users', 'view-user', 'edit-user')) ?>"><a href="<?php echo $this->url('manage-users') ?>">User Management</a></li>
            <li class="<?php echo $cssMenu['/list-system-activity'] ?>"><a href="<?php echo $this->url('list-system-activity') ?>">System Activity</a></li>
	    <li><a href="<?php echo $this->url('admin-logout') ?>">Logout</a></li>
          </ul>
        </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav><!--/.Header -->
