<div class="col-md-2 col-sm-6 col-md-push-7 pad-b20">
    <ul class="footer-nav">
        <li><a href="#">Home</a></li>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Sign In</a> / <a href="#">Sign Up</a></li>
    </ul>
</div>  
<div class="col-md-2 col-sm-6 col-md-push-7 pad-b20">
    <ul class="footer-nav">
        <li><a href="#">Pricing</a></li>
        <li><a href="#">Disclaimer</a></li>
        <li><a href="#">Terms of service</a></li>
        <li><a href="#">Privacy Policy</a></li>
    </ul>
</div>