<!-- Footer -->
<footer class="pad-t40 pad-b20">
    <div class="container pad-t10 pad-b10 font-small">
        <div class="row">
            <?php echo $this->render('layout/footer-menu.phtml') ?>
            <div class="col-md-4 col-sm-6 pad-b20 col-md-pull-4">
                <img src="img/logo_footer.png" />
                <p class="pad-t10">© 2015, DataMatrixSystems. All rights reserved.</p>
            </div>                         
            <div class="col-md-3 col-sm-6 col-md-pull-4 pad-b20">             
                <p class="sprite-phone pad-t5 pad-b5 pad-l40">800.525.3221</p>
                <p class="sprite-email pad-b5 pad-l40"><a href="mailto:info@datamatrixsystems.com">info@datamatrixsystems.com</a></p>
                <ul class="footer-social pad-t10 clearfix">
                    <li><a href="#" class="sprite-facebook text-replace">facebook</a></li>
                    <li><a href="#" class="sprite-twitter text-replace">twitter</a></li>
                    <li><a href="#" class="sprite-gplus text-replace">gplus</a></li>
                </ul>
            </div>                             
        </div>        
    </div>
</footer><!--/.Footer -->    

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery-1.11.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/anim-form.js"></script>  
</body>
</html>
