<!-- Footer -->
<footer class="pad-t40 pad-b20">
    <div class="container pad-t10 pad-b10 font-small">
        <div class="row">
            <?php echo $this->render('layout/footer-menu.phtml') ?>
            <div class="col-lg-3 col-sm-6 pad-b20 col-lg-pull-6">
                <img src="/img/logo_footer.png" />
                <p class="pad-t10">© 2015, Audit Companion.<br/>All rights reserved.</p>
            </div>                         
            <div class="col-lg-3 col-sm-6 col-lg-pull-6 pad-b20">             
                <p class="sprite-phone pad-b5 pad-l40 mar-t5">(844) SOX DATA<br/>(844) 769 3282</p>
                <p class="sprite-email pad-b5 pad-l40"><a href="mailto:support@auditcompanion.biz">support@auditcompanion.biz</a></p>
                <ul class="footer-social pad-t10 clearfix">
                    <li><a href="#" class="sprite-facebook text-replace">facebook</a></li>
                    <li><a href="#" class="sprite-twitter text-replace">twitter</a></li>
                    <li><a href="#" class="sprite-gplus text-replace">gplus</a></li>
                </ul>
            </div>                             
        </div>        
    </div>
</footer><!--/.Footer -->    

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!-- Scripts -->
<?php
    echo $this->headScript()
    //->prependFile($this->basePath('js/app/data-table.js'))
    ->prependFile($this->basePath('js/jquery.dataTables.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/anim-form.js'))
    ->prependFile($this->basePath('js/app/package.js'))
    ->prependFile($this->basePath('js/app/user.js'))
    ->prependFile($this->basePath('js/app/validate.js'))
    ->prependFile($this->basePath('js/app/common.js'))
    ->prependFile($this->basePath('js/jquery-ui-min.js'))
    ->prependFile($this->basePath('js/livequery.js'))
    ->prependFile($this->basePath('/js/jquery-1.11.1.min.js'));
    ?>
</body>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        });         
    </script>
</html>
