<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="img/logo_small.png" /></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right custom-nav">
                <li><a href="#">Home</a></li>            
                <li><a href="#">Pricing</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Sign Up</a></li>
                <li><a href="#" class="btn btn-default btn-small btn-pill mar-t10">Sign In</a></li>
                <li><a href="#"><span class="sprite-cart text-replace">Cart</span></a></li>
                <li><a href="#"><span class="sprite-search text-replace">Search</span></a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>