<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <?php echo $this->headTitle() ?>
        <!-- Bootstrap core CSS 
        <link href="css/bootstrap.css" rel="stylesheet"> -->    
        <!-- Custom styles for this template 
        <link href="css/main.css" rel="stylesheet"> -->    
        
                <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'))                               
                   ->prependStylesheet($this->basePath('css/main.css'))                       
                   ->prependStylesheet($this->basePath('css/bootstrap.css'))
                ;
     ?>
            <!-- <link rel="shortcut icon" href="/img/favicon.ico"  type="image/x-icon" /> -->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
         <link href="img/favicon.ico" rel="shortcut icon">
    </head>

    <body>
        <?php echo $this->render('layout/header-menu.phtml') ?>


        <!--/.Header -->