<?php
include('commonMenuUtility.php');

/* Highlight active menu tab */
$url = $_SERVER['REQUEST_URI'];
$cssMenu = array('/user-account', '/rulebook-list', '/list-extracts', '/analysis-reports', '/purchase-analysis', '/download-utility', 'request-support');
$cssMenu[$url] = 'active';
function headerHighlight($inputArray){
	$url_break_up = explode('/', $_SERVER['REQUEST_URI']);
	foreach ($url_break_up as $url) {
		if (in_array($url, $inputArray)) {
			return 'active';
		}
	}
}
$mobileDetectService = $this->mobile_detect_view_helper();
$isMobile = $mobileDetectService->isMobile();
$isTablet = $mobileDetectService->isTablet();
$hideRulebook = false;
if ($isMobile == true || $isTablet == true) {
    $hideRulebook = true;
}
$hideForRole = false;
$roleSession = new Zend\Session\Container('role');
if ($roleSession->roleName == 'associate' OR $roleSession->roleName == 'admin') {
    $hideForRole = true;
}
?>

<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php echo $this->headTitle() ?>
        <!-- Bootstrap core CSS -->    
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/jquery.dataTables.css" rel="stylesheet">
	<link href="/css/bootstrap-multiselect.css" rel="stylesheet">
        <!-- Custom styles for this template -->    

        <link href="/css/main.css" rel="stylesheet">
        <link href="/img/favicon.ico" rel="shortcut icon">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $logRef ?>"><img src="/img/logo_small.png" /></a>
                </div>
                <div id="navbar">
                    <ul class="nav navbar-nav navbar-right custom-nav">
                        <li class="navbar-text mar-t10">Welcome <?php echo $userName ?></li>      
                        <li class="app-cart"><a href="<?php echo $this->url('display-cart') ?>"><span class="sprite-cart text-replace">Cart</span></a></li>
                        <li class="dropdown custom-dd">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="<?php echo $cssMenu['/user-account'] ?>" ><a href="<?php echo $this->url('user-account') ?>">My Account</a></li>
                                <?php if (!$hideRulebook AND !$hideForRole):?>
	                                <li class="<?php echo headerHighlight(array('rulebook-list', 'modify-rulebook', 'complete-rule-book')); ?>"><a href="<?php echo $this->url('rulebook-list') ?>">Create Rulebook</a></li>
                                        <li class="<?php echo $cssMenu['/analysis-request'] ?>"><a href="<?php echo $this->url('analysis-request') ?>">Request Analysis</a></li>
                                <?php endif;?>
                                <li class="<?php echo $cssMenu['/list-extracts'] ?>"><a href="<?php echo $this->url('list-extracts') ?>">SAP Extracts</a></li>
				<?php if (!$hideForRole):?>
		                        <li class="<?php echo headerHighlight(array('analysis-reports', 'analysis-in-queue-reports')) ?>"><a href="<?php echo $this->url('analysis-reports') ?>">My Analysis</a></li>
		                        <li class="<?php echo headerHighlight(array('purchase-analysis', 'cart', 'checkout', 'confirm-order', 'thank-you')); ?>"><a href="<?php echo $this->url('purchase-analysis') ?>">Purchase Analysis</a></li>
				<?php endif;?>
                                <li class="<?php echo $cssMenu['/download-utility'] ?>"><a href="<?php echo $this->url('download-utility') ?>">Download Utility</a></li>
                                <li class="<?php echo $cssMenu['/request-support'] ?>"><a href="<?php echo $this->url('request-support') ?>">Request Support</a></li>
                                <li><a href="<?php echo $this->url('sign-out') ?>">Logout</a></li>            
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav><!--/.Header -->


        <!--/.Header -->
