<body>
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><img src="img/logo_small.png" /></a>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav navbar-right custom-nav">
        <li class="navbar-text mar-t10">Welcome Admin User</li>                        
   <li class="dropdown custom-dd">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><a href="#">Dashboard</a></li>
        <li class="active"><a href="#">User Management</a></li>
      </ul>
    </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav><!--/.Header -->

<div class="container">
   <div class="clearfix">
    <h1 class="pull-left">User Management</h1>
    <h2 class="pull-right font-family-md pad-t5">Available Analysis Credits <span class="badge custom-badge mar-l10 font-size-l">20</span></h2>
    </div>
    <div class="table-responsive">
    <table class="table custom-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th class="txtr">Available Credits</th>
                <th class="txtr">Last Login Date & Time</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody id="accordion" role="tablist" aria-multiselectable="true">
            <tr>
                <td>Name one</td>
                <td>Audit@xyz.com</td>
                <td class="txtr">20</td>
                <td class="txtr">03/26/2015</td>
                <td>Active</td>
                <td>
                    <a href="#" class="action-icon">Edit</a>
                    <a href="#" class="action-icon mar-l20" data-toggle="tooltip" data-placement="top" title="Download">Blog</a>
                    <a href="#" class="action-icon text-replace sprite-delete mar-l20" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                </td>
            </tr>
          <tr>
                <td>Name one</td>
                <td>AuditCompanion@xyz.com</td>
                <td class="txtr">20</td>
                <td class="txtr">03/26/2015</td>
                <td>Inactive</td>
                <td>
                    <a href="#" class="action-icon" data-toggle="tooltip" data-placement="top" title="Extend Time">Edit</a>
                    <a href="#" class="action-icon mar-l20" data-toggle="tooltip" data-placement="top" title="Download">Blog</a>
                    <a href="#" class="action-icon text-replace sprite-delete mar-l20" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                </td>
            </tr>
         <tr>
                <td>Name one</td>
                <td>Audit@xyz.com</td>
                <td class="txtr">20</td>
                <td class="txtr">03/26/2015</td>
                <td>Active</td>
                <td>
                    <a href="#" class="action-icon ">Edit</a>
                    <a href="#" class="action-icon  mar-l20" data-toggle="tooltip" data-placement="top" title="Download">Blog</a>
                    <a href="#" class="action-icon text-replace sprite-delete mar-l20" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                </td>
            </tr>
             <tr>
                <td>Name one</td>
                <td>AuditCompanion-01@xyz.com</td>
                <td class="txtr">20</td>
                <td class="txtr">03/26/2015</td>
                <td>Inactive</td>
                <td>
                    <a href="#" class="action-icon " data-toggle="tooltip" data-placement="top" title="Extend Time">Edit</a>
                    <a href="#" class="action-icon  mar-l20" data-toggle="tooltip" data-placement="top" title="Download">Blog</a>
                    <a href="#" class="action-icon text-replace sprite-delete mar-l20" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                </td>
            </tr>

            <tr>
                <td>Name one</td>
                <td>Audit_234@xyz.com</td>
                <td class="txtr">20</td>
                <td class="txtr">03/26/2015</td>
                <td>Inactive</td>
                <td>
                    <a href="#" class="action-icon ">Edit</a>
                    <a href="#" class="action-icon mar-l20" data-toggle="tooltip" data-placement="top" title="Download">Blog</a>
                    <a href="#" class="action-icon text-replace sprite-delete mar-l20" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                </td>
            </tr>

            <tr>
                <td>Name one</td>
                <td>Audit_098@xyz.com</td>
                <td class="txtr">20</td>
                <td class="txtr">03/26/2015</td>
                <td>Active</td>
                <td>
                    <a href="#" class="action-icon " data-toggle="tooltip" data-placement="top" title="Extend Time">Edit</a>
                    <a href="#" class="action-icon mar-l20" data-toggle="tooltip" data-placement="top" title="Download">Blog</a>
                    <a href="#" class="action-icon text-replace sprite-delete mar-l20" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                </td>
            </tr>

            <tr>
                <td>Name one</td>
                <td>Audit-123@xyz.com</td>
                <td class="txtr">20</td>
                <td class="txtr">03/26/2015</td>
                <td>Inactive</td>
                <td>
                    <a href="#" class="action-icon">Edit</a>
                    <a href="#" class="action-icon mar-l20" data-toggle="tooltip" data-placement="top" title="Download">Blog</a>
                    <a href="#" class="action-icon text-replace sprite-delete mar-l20" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                </td>
            </tr>
            <tr>
                <td>Name one</td>
                <td>Audit.908@xyz.com</td>
                <td class="txtr">20</td>
                <td class="txtr">03/26/2015</td>
                <td>Active</td>
                <td>
                    <a href="#" class="action-icon " data-toggle="tooltip" data-placement="top" title="Extend Time">Edit</a>
                    <a href="#" class="action-icon mar-l20" data-toggle="tooltip" data-placement="top" title="Download">Blog</a>
                    <a href="#" class="action-icon text-replace sprite-delete mar-l20" data-toggle="tooltip" data-placement="top" title="Delete">Delete</a>
                </td>
            </tr>

        </tbody>
    </table>   
    </div>                 
</div>

<!-- Footer -->
<footer class="pad-t10 pad-b10">
   <div class="container pad-t0 pad-b0 font-small">
   <div class="row">

       <div class="col-md-7 col-sm-6 pad-b10 col-md-pull-0">
<!--             <img src="img/logo_footer.png" />-->
         <p class="pad-t20">© 2015, Audit Companion. All rights reserved.</p>
       </div>                         
       <div class="col-md-5 col-sm-6 col-md-pull-0 pad-t20" >             
<ul class="footer-social pad-t10 clearfix" style="float: right;">
             <li><a href="#" class="sprite-facebook text-replace">facebook</a></li>
             <li><a href="#" class="sprite-twitter text-replace">twitter</a></li>
             <li><a href="#" class="sprite-gplus text-replace">gplus</a></li>
         </ul>
       </div>                             
   </div>        
   </div>
</footer><!--/.Footer -->
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery-1.11.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })      
</script>
</body>
