<?php
$form = $this->adminLoginForm;
$form->prepare();
$form->setAttribute('name', 'addUser');
$form->setAttribute('id', 'addUser');
$form->setAttribute('method', 'post');
$email = $this->userDetails['userEmail'];

?>
<section class="ts-sysad-login">
    <h3>Administrator Access</h3>
    <div class="ts-sysad-warning">
      <span class="ts-info"></span>
      <p>If you were sent to this page from a link obtained from an untrusted source please proceed with caution or validate the link source before continuing</p>
    </div>
    <p class="ts-valtxt">You have requested access to an administrative function in <strong>QGrid</strong> and are required to validate your credentials below</p>
    <?php echo $this->form()->openTag($form); ?>
        <div class="mar-b15">
           <label class="ts-lbl-txt">Username: </label> <span class="ts-emailtxt"><?php echo $account->getUserName(); ?></span> <a href="<?php echo $this->url('logout'); ?>" class="ts-link">Not You?</a>
        </div>

        <div class="mar-b15">
            <label class="ts-lbl-txt" >Password <span>*</span></label>
            <?php echo $this->formRow($form->get('password')) . "\n"; ?> 
            <p style="margin-left: 184px;" class="ts-error" id="passwordErrorMsg"><?php echo $this->errorMessage; ?></p>

        </div>

        <div class="mar-b15">
            <button class="btn-confirm">Confirm</button> <a href="/" class="ts-link">Cancel</a>
        </div>                
    <?php echo $this->form()->closeTag($form); ?>
</section>   




