<?php
    $form = $this->forgotPasswordForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('forgot-password'));
    $form->setAttribute('name', 'forgot_password');
    $form->setAttribute('id', 'forgot_password');
    $form->setAttribute('method', 'post');   
    $form->setAttribute('class', 'row');  
?>
<!-- Sign In Block Start -->
<div class="container m-h550">        
        <div class="row pad-b30">
         <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">              
                <h2 class="font-size-xl txtc mar-t20">Forgot Password?</h2>                 
              
                <?php if ($this->errorMessage) { ?>                    
                    <script>
                        setTimeout("$('.alert-error').fadeOut(2000);", 5000);                       
                    </script>                    
                    <div class="alert-error"><?php echo $this->errorMessage; ?></div>
                <?php } ?>
              
                 <?php echo $this->form()->openTag($form); ?>              
                  <div class="col-sm-12">
                    <div class="form-group" id="emailErrorClass">
                        <span class="form-control-anim">                                        
                                <?php echo $this->formRow($form->get('email')); ?>
                            <label class="form-control-label">                              
                              <span id="emailErrorMsg" class="form-control-label-content">Email Address</span>
                            </label>
                        </span>                   
                    </div>                           
                  </div> 
                  
                  <div class="col-sm-12">
                        <div class="form-group">                        
                           <?php echo $this->formRow($form->get('button_forgot_password')); ?>
                        </div>                                            
                  </div>
                  
                  <div class="col-sm-12">
                        <div class="form-group mar-t20">
                          Returning Customer? <a href="<?php echo $this->url('sign-in') ?>">Sign In</a>
                        </div>                      
                  </div> 
            <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>        
      </div>    
<!--/.Sign In Block Start -->