<?php
    $form = $this->forgotPasswordForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('forgot_password'));
    $form->setAttribute('method', 'post');
?>
<section class="ts-login-wrapper">
    <h1 class="ts-logo"><span></span><!--img src="/images/qgrid_big_logo.png" alt="Qgrid" title="Qgrid" /--></h1>
    <section class="ts-login">
        <h3>Forgot Password</h3>
        <?php echo $this->form()->openTag($form); ?>            
            <div class="ts-login-cont">
                <?php if ($this->errorMessage) { ?>
                    <div class="ts-errormsg"><?php echo $this->errorMessage; ?></div>
                <?php } else if ($this->successMessage) { ?>
                    <div class="ts-success"><?php echo $this->successMessage; ?></div>
                <?php } ?>
                <div class="ts-overfl">
                    <label>Username</label>
                    <div class="ts-fl">
                        <?php echo $this->formRow($form->get('user_name')); ?>
                        <p id="user_nameErrorMsg" class="ts-error"></p>
                    </div>
                </div>	
                <div class="ts-fr pad-t20">
                    <?php echo $this->formRow($form->get('submit_button')); ?>
                    <a class="ts-cancel" href="/login">Cancel</a>
                </div>												
            </div>
        <?php echo $this->form()->closeTag($form); ?>
    </section>				
</section>
