<?php
    $form = $this->resetForgotPasswordForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('reset-password'));
    $form->setAttribute('name', 'reset_password');
    $form->setAttribute('id', 'reset_password');
    $form->setAttribute('method', 'post');   
    $form->setAttribute('class', 'row');   
?>
<!-- Sign In Block Start -->
<div class="container m-h550">        
        <div class="row pad-b30">
         <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
              <?php if (isset($this->setPassword)):?>
                <h2 class="font-size-xl txtc mar-t20">Set Password</h2>   
              <?php else:?>
                <h2 class="font-size-xl txtc mar-t20">Reset Password</h2>   
              <?php endif;?>
              
                <?php if ($this->errorMessage) { ?>                    
                    <script>
                        setTimeout("$('.alert-error').fadeOut(2000);", 5000);                       
                    </script>                    
                    <div class="alert-error"><?php 
                    
                    //print_r($this->errorMessage);
                    
                    foreach($this->errorMessage as $msg){                    
                     echo $msg . "<br />";    
                    }
                    
                    ?></div>
                <?php } ?>
              
                 <?php echo $this->form()->openTag($form); ?>      
                      <input type="hidden" id="verification_code" name="verification_code" value="<?php echo $this->verification_code; ?>"/>
                  <div class="col-sm-12">
                    <div class="form-group" id="new_passwordErrorClass">
                        <span class="form-control-anim">                                        
                                <?php echo $this->formRow($form->get('new_password')); ?>
                            <label class="form-control-label">                              
                              <span id="new_passwordErrorMsg" class="form-control-label-content">Password</span>
                            </label>
                        </span>                   
                    </div>                           
                  </div> 
                    
                <div class="col-sm-12">
                    <div class="form-group" id="confirm_new_passwordErrorClass">
                        <span class="form-control-anim">                                        
                                <?php echo $this->formRow($form->get('confirm_new_password')); ?>
                            <label class="form-control-label">                              
                              <span id="confirm_new_passwordErrorMsg" class="form-control-label-content">Confirm password</span>
                            </label>
                        </span>                   
                    </div>                           
                  </div>   
                <div class="col-sm-12" id='passwordCriteria' style='display:none'>
                    <p class="alert alert-warning font-size-small mar-t0">Password must be at least 8 characters and should contains at least 1 lower case letter, upper case letter, number and special character.</p>
                </div>
                  <div class="col-sm-12">
                        <div class="form-group">                        
                           <?php echo $this->formRow($form->get('reset_password_button')); ?>
                        </div>                                            
                  </div>
                    
            <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>        
      </div>    
<!--/.Sign In Block Start -->