<?php
    $form = $this->resetPasswordForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('reset_password').$this->resetPasswordVerificationCode);
    $form->setAttribute('method', 'post');
?>
<section class="ts-login-wrapper">
    <h1 class="ts-logo"><span></span><!--img src="/images/qgrid_big_logo.png" alt="Qgrid" title="Qgrid" /--></h1>
    <section class="ts-login">
        <h3>Reset Password</h3>
        <?php echo $this->form()->openTag($form); ?>
            <?php if ($this->errorMessage) { ?>
                <div class="ts-error"><?php echo $this->errorMessage; ?></div>
            <?php } ?>
            <div class="ts-login-cont reset-pw">
                <div class="ts-overfl">
                    <label>New Password</label>
                    <div class="ts-fl">
                        <?php echo $this->formRow($form->get('new_password')); ?>
                        <p id="new_passwordErrorMsg" class="ts-error"></p>
                    </div>
                    <label>Confirm New Password</label>
                    <div class="ts-fl">
                        <?php echo $this->formRow($form->get('confirm_new_password')); ?>
                        <p id="confirm_new_passwordErrorMsg" class="ts-error"></p>
                    </div>							
                </div>	
                <div class="ts-fr pad-t20">
                    <?php echo $this->formRow($form->get('submit_button')); ?>
                </div>												
            </div>
        <?php echo $this->form()->closeTag($form); ?>
    </section>				
</section>