<?php
$userObject = $this->userObject;
$userId = $userObject->getId();
$userCreditHistory = $this->userCreditHistory;

/* Hide adjust credtis model for inactive and blocked user */
$detailModalId = "#detailsmodal";
$idForDetailsModal = "";
if($userObject->getIsBlocked() == 1 || $userObject->getActiveFlag() == 0) {
    $detailModalId = "";
    $idForDetailsModal = "detailsModalHided";
}
?>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 col-lg-offset-2 col-md-offset-1 mar-b40">
            <div class="clearfix">
                <h1 class="txtc">User View</h1>        
            </div>

            <?php
                echo $this->partial('user-credit-history.phtml', array(
                    'userCreditHistory' => $userCreditHistory,
                    'userId' => $userId
                ));
              ?>

            <hr class="clearfix">
            <div class="clearfix pad-t10 pad-b10"> 
                <a href="<?php echo $this->url('admin-edit-user', array('userId' => $userId)) ?>" class='btn btn-default btn-small'>Edit</a>
                <a href="#" id="<?php echo $idForDetailsModal; ?>" data-target="<?php echo $detailModalId; ?>" data-toggle="modal" class='btn btn-default btn-small mar-l20'>Adjust Analysis Credits</a>
                <a attr-user-id="<?php echo $userId; ?>" class='btn btn-default btn-small mar-l20 admin-reset-password'>Reset Password</a>
            </div>
            <hr class="clearfix">
            
            <?php if ($this->successMessage) { ?>            
                <script>
                    setTimeout("$('.alert-success').fadeOut(2000);", 5000);
                </script>
                <div class="alert-success"><?php echo $this->successMessage; ?></div>
            <?php } ?>
            <div class="alert-success" id="span_alert_success" style="display:none"></div>
            <div class="alert-error" id="span_alert_error" style="display:none"></div>
          <!--  <div class="alert-success" style="display:none"></div>
            <div class="alert-error" style="display:none"></div> -->
            <div class="row">
               <div class="clearfix">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>First Name</label>
                        <div><?php echo $userObject->getFirstName(); ?></div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Last Name</label>
                        <div><?php echo $userObject->getLastName(); ?></div>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Email Address</label>
                        <div><?php echo $userObject->getUsername(); ?></div>
                    </div>
                </div> 
                </div> 
                <div class="clearfix">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Address #1</label>
                        <div><?php echo $userObject->getAddress1(); ?></div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Address #2</label>
                        <div><?php echo $userObject->getAddress2(); ?></div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>City</label>
                        <div><?php echo $userObject->getCity(); ?></div>
                    </div>
                </div>
                </div>
                <div class="clearfix">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>State</label>
                        <div><?php echo $userObject->getState(); ?></div>
                    </div>
                </div> 
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Country</label>
                        <div><?php echo $userObject->getCountry(); ?></div>
                    </div>
                </div>  
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Zip Code</label>
                        <div><?php echo $userObject->getZipcode(); ?></div>
                    </div>
                </div>                                                                
                </div> 
            </div>

            <?php
            echo $this->partial('adjust-credits-model.phtml', array(
                'remainingPoints' => $userCreditHistory['remainingPoints'],            
            ))
            ?>

        </div>
    </div>
</div>                    

